export const APP_NAME = 'SynapseHub';
export const APP_DESCRIPTION = 'AI-Native Business Operating System';
export const APP_VERSION = '1.0.0';

export const TIER_LIMITS = {
  tier_1: {
    name: 'Managed Lead Recovery',
    price: 297,
    monthly_interactions: 500,
    agents: 1,
    users: 2,
    automations: 5,
    knowledge_base_entries: 100,
    channels: ['chat'] as const,
    features: [
      'ai_chat_widget',
      'lead_capture',
      'basic_crm',
      'email_notifications',
      'basic_analytics',
      'appointment_booking',
      'review_monitoring',
    ],
  },
  tier_2: {
    name: 'Strategic Efficiency Suite',
    price: 497,
    monthly_interactions: 2000,
    agents: 3,
    users: 10,
    automations: 25,
    knowledge_base_entries: 500,
    channels: ['chat', 'sms'] as const,
    features: [
      'ai_chat_widget',
      'sms_ai',
      'lead_capture',
      'full_crm',
      'pipeline_management',
      'automation_engine',
      'email_notifications',
      'sms_notifications',
      'advanced_analytics',
      'appointment_booking',
      'calendar_sync',
      'review_management',
      'review_responses',
      'custom_fields',
      'team_management',
      'api_access',
    ],
  },
  tier_3: {
    name: 'Elite Enterprise Partnership',
    price: 897,
    monthly_interactions: 10000,
    agents: 10,
    users: 50,
    automations: 100,
    knowledge_base_entries: 2000,
    channels: ['chat', 'voice', 'sms', 'email'] as const,
    features: [
      'ai_chat_widget',
      'ai_voice',
      'sms_ai',
      'email_ai',
      'lead_capture',
      'full_crm',
      'pipeline_management',
      'advanced_automation_engine',
      'all_notifications',
      'enterprise_analytics',
      'ai_insights',
      'appointment_booking',
      'calendar_sync',
      'review_management',
      'review_responses',
      'ai_review_drafts',
      'custom_fields',
      'team_management',
      'role_management',
      'api_access',
      'webhooks',
      'white_label',
      'priority_support',
      'dedicated_success_manager',
      'custom_integrations',
    ],
  },
} as const;

export const ROUTES = {
  // Public
  HOME: '/',
  PRICING: '/pricing',
  DEMO: '/demo',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',

  // Onboarding
  ONBOARDING: '/onboarding',
  ONBOARDING_INTAKE: '/onboarding/intake',
  ONBOARDING_KB: '/onboarding/knowledge-base',
  ONBOARDING_AGENT: '/onboarding/agent-config',
  ONBOARDING_TEST: '/onboarding/test',
  ONBOARDING_LAUNCH: '/onboarding/launch',

  // Dashboard
  DASHBOARD: '/dashboard',
  DASHBOARD_CONVERSATIONS: '/dashboard/conversations',
  DASHBOARD_LEADS: '/dashboard/leads',
  DASHBOARD_BOOKINGS: '/dashboard/bookings',
  DASHBOARD_AUTOMATIONS: '/dashboard/automations',
  DASHBOARD_REVIEWS: '/dashboard/reviews',
  DASHBOARD_ANALYTICS: '/dashboard/analytics',
  DASHBOARD_AGENTS: '/dashboard/agents',
  DASHBOARD_KB: '/dashboard/knowledge-base',
  DASHBOARD_SETTINGS: '/dashboard/settings',
  DASHBOARD_TEAM: '/dashboard/team',
  DASHBOARD_BILLING: '/dashboard/billing',
} as const;

export const AGENT_MODELS = [
  { value: 'gemini-2.0-flash', label: 'Gemini 2.0 Flash (Fast)' },
  { value: 'gemini-2.0-pro', label: 'Gemini 2.0 Pro (Balanced)' },
  { value: 'gemini-1.5-pro', label: 'Gemini 1.5 Pro (Legacy)' },
] as const;

export const INDUSTRIES = [
  'general',
  'healthcare',
  'dental',
  'legal',
  'real_estate',
  'home_services',
  'automotive',
  'restaurant',
  'fitness',
  'salon_spa',
  'financial',
  'insurance',
  'education',
  'ecommerce',
  'saas',
  'agency',
  'other',
] as const;

export const LEAD_STAGE_COLORS: Record<string, string> = {
  new: '#6366f1',
  contacted: '#8b5cf6',
  qualified: '#3b82f6',
  proposal: '#f59e0b',
  negotiation: '#f97316',
  won: '#22c55e',
  lost: '#ef4444',
};

export const TEMPERATURE_COLORS: Record<string, string> = {
  hot: '#ef4444',
  warm: '#f59e0b',
  cold: '#3b82f6',
};
